### PR TITLE
More files, more files of specific types

### PR DESCRIPTION
**Pull request by djbrooke**
We want more than 10 files in the dataset, so I'm adding a few more to CMS

### CODE REVIEW

**Review by pdurbin — APPROVED** [review]
I'm glad to see these are all small.

**Comment by djbrooke** [comment]
@pdurbin Can you re-review? I put up this PR prematurely. I meant to just create a branch. Thanks!

**Comment by pdurbin** [comment]
@djbrooke it still looks fine. "data users document.pdf" has spaces in it but should work. I made an effort to support spaces in the names of data files.

**Comment by djbrooke** [comment]
@pdurbin - thanks for the quick review, I'll merge this.

**Pull request merged**
