### PR TITLE
add PUMS data #27

### LINKED ISSUE #27: Add PUMS sample data for OpenDP
See https://github.com/opendp/dpcreator/issues/308

1 data file: https://github.com/opendp/PSI/blob/develop/data/PUMS5extract10000.csv

metadata from https://www.census.gov/data/datasets/2000/dec/microdata.html

### PR DESCRIPTION
**Pull request by pdurbin**
Closes #27 

OpenDP has been using PUMS data in demos. It's currently on a Dataverse test server put we'd like to add it more permanently to the sample data repo.

Here's how the dataverse and dataset look in the search cards:

Screen Shot 2021-09-20 at 2 49 45 PM

Here's a preview of the dataset:

Screen Shot 2021-09-20 at 2 50 10 PM

Here's a preview of the file:

Screen Shot 2021-09-20 at 2 50 48 PM

### CODE REVIEW

**Review by djbrooke — APPROVED** [review]
This matches the expected folder format (collection/dataset/file) for other sample data sets. @pdurbin mentioned that for this to be useful it would be helpful to have this issue prioritized, since this data relies on restrictions:

https://github.com/IQSS/dataverse-sample-data/issues/5

**Comment by pdurbin** [comment]
@djbrooke good catch that we already had an open issue about optionally restricting a file!

**Comment by kcondon** [comment]
@pdurbin Are we merging directly into master?
Oh, nevermind. Sample data repo

**Comment by pdurbin** [comment]
@kcondon yes, master is fine.

**Pull request merged**
